// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoto1H8HrOsmbH3MmN9vaFJ8uykuv1Qjk',
    appId: '1:91832232661:web:16bf925fd8fe162c12505c',
    messagingSenderId: '91832232661',
    projectId: 'athletic-workout',
    authDomain: 'athletic-workout.firebaseapp.com',
    storageBucket: 'athletic-workout.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1x4CmsBgc-pxbFbdkMOJzdxTY35Grd8s',
    appId: '1:91832232661:android:029654aa728cd0d412505c',
    messagingSenderId: '91832232661',
    projectId: 'athletic-workout',
    storageBucket: 'athletic-workout.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDos5JpPggCfUQVKe55WJY6na91Iw1VEzw',
    appId: '1:91832232661:ios:d4dcc49dd57c27c312505c',
    messagingSenderId: '91832232661',
    projectId: 'athletic-workout',
    storageBucket: 'athletic-workout.appspot.com',
    iosBundleId: 'com.example.athletic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDos5JpPggCfUQVKe55WJY6na91Iw1VEzw',
    appId: '1:91832232661:ios:d4dcc49dd57c27c312505c',
    messagingSenderId: '91832232661',
    projectId: 'athletic-workout',
    storageBucket: 'athletic-workout.appspot.com',
    iosBundleId: 'com.example.athletic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoto1H8HrOsmbH3MmN9vaFJ8uykuv1Qjk',
    appId: '1:91832232661:web:dc3dfb38e50541ee12505c',
    messagingSenderId: '91832232661',
    projectId: 'athletic-workout',
    authDomain: 'athletic-workout.firebaseapp.com',
    storageBucket: 'athletic-workout.appspot.com',
  );

}